version: "3"
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network

  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
